// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: comms/comms.proto

package comms

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Conn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
}

func (x *Conn) Reset() {
	*x = Conn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comms_comms_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Conn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conn) ProtoMessage() {}

func (x *Conn) ProtoReflect() protoreflect.Message {
	mi := &file_comms_comms_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conn.ProtoReflect.Descriptor instead.
func (*Conn) Descriptor() ([]byte, []int) {
	return file_comms_comms_proto_rawDescGZIP(), []int{0}
}

func (x *Conn) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comms_comms_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_comms_comms_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_comms_comms_proto_rawDescGZIP(), []int{1}
}

type Command struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	C string `protobuf:"bytes,1,opt,name=c,proto3" json:"c,omitempty"`
}

func (x *Command) Reset() {
	*x = Command{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comms_comms_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_comms_comms_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_comms_comms_proto_rawDescGZIP(), []int{2}
}

func (x *Command) GetC() string {
	if x != nil {
		return x.C
	}
	return ""
}

type LocateCity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NombrePlaneta string `protobuf:"bytes,1,opt,name=nombrePlaneta,proto3" json:"nombrePlaneta,omitempty"`
	NombreCiudad  string `protobuf:"bytes,2,opt,name=nombreCiudad,proto3" json:"nombreCiudad,omitempty"`
}

func (x *LocateCity) Reset() {
	*x = LocateCity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comms_comms_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocateCity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocateCity) ProtoMessage() {}

func (x *LocateCity) ProtoReflect() protoreflect.Message {
	mi := &file_comms_comms_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocateCity.ProtoReflect.Descriptor instead.
func (*LocateCity) Descriptor() ([]byte, []int) {
	return file_comms_comms_proto_rawDescGZIP(), []int{3}
}

func (x *LocateCity) GetNombrePlaneta() string {
	if x != nil {
		return x.NombrePlaneta
	}
	return ""
}

func (x *LocateCity) GetNombreCiudad() string {
	if x != nil {
		return x.NombreCiudad
	}
	return ""
}

type NumberRebelds struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NR int32 `protobuf:"varint,1,opt,name=nR,proto3" json:"nR,omitempty"`
}

func (x *NumberRebelds) Reset() {
	*x = NumberRebelds{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comms_comms_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NumberRebelds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumberRebelds) ProtoMessage() {}

func (x *NumberRebelds) ProtoReflect() protoreflect.Message {
	mi := &file_comms_comms_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumberRebelds.ProtoReflect.Descriptor instead.
func (*NumberRebelds) Descriptor() ([]byte, []int) {
	return file_comms_comms_proto_rawDescGZIP(), []int{4}
}

func (x *NumberRebelds) GetNR() int32 {
	if x != nil {
		return x.NR
	}
	return 0
}

type DataCity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NombrePlaneta string `protobuf:"bytes,1,opt,name=nombre_planeta,json=nombrePlaneta,proto3" json:"nombre_planeta,omitempty"`
	NombreCiudad  string `protobuf:"bytes,2,opt,name=nombre_ciudad,json=nombreCiudad,proto3" json:"nombre_ciudad,omitempty"`
	NuevoValor    int32  `protobuf:"varint,3,opt,name=nuevo_valor,json=nuevoValor,proto3" json:"nuevo_valor,omitempty"` // 0 si es que no se escribe uno
}

func (x *DataCity) Reset() {
	*x = DataCity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comms_comms_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataCity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataCity) ProtoMessage() {}

func (x *DataCity) ProtoReflect() protoreflect.Message {
	mi := &file_comms_comms_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataCity.ProtoReflect.Descriptor instead.
func (*DataCity) Descriptor() ([]byte, []int) {
	return file_comms_comms_proto_rawDescGZIP(), []int{5}
}

func (x *DataCity) GetNombrePlaneta() string {
	if x != nil {
		return x.NombrePlaneta
	}
	return ""
}

func (x *DataCity) GetNombreCiudad() string {
	if x != nil {
		return x.NombreCiudad
	}
	return ""
}

func (x *DataCity) GetNuevoValor() int32 {
	if x != nil {
		return x.NuevoValor
	}
	return 0
}

type ChangeNameCity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NombrePlaneta string `protobuf:"bytes,1,opt,name=nombre_planeta,json=nombrePlaneta,proto3" json:"nombre_planeta,omitempty"`
	NombreCiudad  string `protobuf:"bytes,2,opt,name=nombre_ciudad,json=nombreCiudad,proto3" json:"nombre_ciudad,omitempty"`
	NuevoNombre   string `protobuf:"bytes,3,opt,name=nuevo_nombre,json=nuevoNombre,proto3" json:"nuevo_nombre,omitempty"`
}

func (x *ChangeNameCity) Reset() {
	*x = ChangeNameCity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comms_comms_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeNameCity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeNameCity) ProtoMessage() {}

func (x *ChangeNameCity) ProtoReflect() protoreflect.Message {
	mi := &file_comms_comms_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeNameCity.ProtoReflect.Descriptor instead.
func (*ChangeNameCity) Descriptor() ([]byte, []int) {
	return file_comms_comms_proto_rawDescGZIP(), []int{6}
}

func (x *ChangeNameCity) GetNombrePlaneta() string {
	if x != nil {
		return x.NombrePlaneta
	}
	return ""
}

func (x *ChangeNameCity) GetNombreCiudad() string {
	if x != nil {
		return x.NombreCiudad
	}
	return ""
}

func (x *ChangeNameCity) GetNuevoNombre() string {
	if x != nil {
		return x.NuevoNombre
	}
	return ""
}

type Clock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y int32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Z int32 `protobuf:"varint,3,opt,name=z,proto3" json:"z,omitempty"`
}

func (x *Clock) Reset() {
	*x = Clock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comms_comms_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Clock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Clock) ProtoMessage() {}

func (x *Clock) ProtoReflect() protoreflect.Message {
	mi := &file_comms_comms_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Clock.ProtoReflect.Descriptor instead.
func (*Clock) Descriptor() ([]byte, []int) {
	return file_comms_comms_proto_rawDescGZIP(), []int{7}
}

func (x *Clock) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Clock) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Clock) GetZ() int32 {
	if x != nil {
		return x.Z
	}
	return 0
}

type Planet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Planet string `protobuf:"bytes,1,opt,name=planet,proto3" json:"planet,omitempty"`
}

func (x *Planet) Reset() {
	*x = Planet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comms_comms_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Planet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Planet) ProtoMessage() {}

func (x *Planet) ProtoReflect() protoreflect.Message {
	mi := &file_comms_comms_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Planet.ProtoReflect.Descriptor instead.
func (*Planet) Descriptor() ([]byte, []int) {
	return file_comms_comms_proto_rawDescGZIP(), []int{8}
}

func (x *Planet) GetPlanet() string {
	if x != nil {
		return x.Planet
	}
	return ""
}

var File_comms_comms_proto protoreflect.FileDescriptor

var file_comms_comms_proto_rawDesc = []byte{
	0x0a, 0x11, 0x63, 0x6f, 0x6d, 0x6d, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x63, 0x6f, 0x6d, 0x6d, 0x73, 0x22, 0x16, 0x0a, 0x04, 0x43, 0x6f,
	0x6e, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x70, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x17, 0x0a, 0x07, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x0c, 0x0a, 0x01, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x01, 0x63, 0x22, 0x56, 0x0a, 0x0a, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x65, 0x43, 0x69,
	0x74, 0x79, 0x12, 0x24, 0x0a, 0x0d, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x50, 0x6c, 0x61, 0x6e,
	0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6e, 0x6f, 0x6d, 0x62, 0x72,
	0x65, 0x50, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x61, 0x12, 0x22, 0x0a, 0x0c, 0x6e, 0x6f, 0x6d, 0x62,
	0x72, 0x65, 0x43, 0x69, 0x75, 0x64, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x43, 0x69, 0x75, 0x64, 0x61, 0x64, 0x22, 0x1f, 0x0a, 0x0d,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x62, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x0e, 0x0a,
	0x02, 0x6e, 0x52, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x6e, 0x52, 0x22, 0x77, 0x0a,
	0x08, 0x44, 0x61, 0x74, 0x61, 0x43, 0x69, 0x74, 0x79, 0x12, 0x25, 0x0a, 0x0e, 0x6e, 0x6f, 0x6d,
	0x62, 0x72, 0x65, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x50, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x61,
	0x12, 0x23, 0x0a, 0x0d, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x5f, 0x63, 0x69, 0x75, 0x64, 0x61,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x43,
	0x69, 0x75, 0x64, 0x61, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x75, 0x65, 0x76, 0x6f, 0x5f, 0x76,
	0x61, 0x6c, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6e, 0x75, 0x65, 0x76,
	0x6f, 0x56, 0x61, 0x6c, 0x6f, 0x72, 0x22, 0x7f, 0x0a, 0x0e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x43, 0x69, 0x74, 0x79, 0x12, 0x25, 0x0a, 0x0e, 0x6e, 0x6f, 0x6d, 0x62,
	0x72, 0x65, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x50, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x61, 0x12,
	0x23, 0x0a, 0x0d, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x5f, 0x63, 0x69, 0x75, 0x64, 0x61, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x43, 0x69,
	0x75, 0x64, 0x61, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x6e, 0x75, 0x65, 0x76, 0x6f, 0x5f, 0x6e, 0x6f,
	0x6d, 0x62, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6e, 0x75, 0x65, 0x76,
	0x6f, 0x4e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x22, 0x31, 0x0a, 0x05, 0x63, 0x6c, 0x6f, 0x63, 0x6b,
	0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x78, 0x12, 0x0c,
	0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x79, 0x12, 0x0c, 0x0a, 0x01,
	0x7a, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x7a, 0x22, 0x20, 0x0a, 0x06, 0x50, 0x6c,
	0x61, 0x6e, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x32, 0x6f, 0x0a, 0x06,
	0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x12, 0x26, 0x0a, 0x05, 0x67, 0x65, 0x74, 0x49, 0x50, 0x12,
	0x0e, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x73, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x1a,
	0x0b, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x22, 0x00, 0x12, 0x3d,
	0x0a, 0x10, 0x67, 0x65, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x62, 0x65, 0x6c,
	0x64, 0x73, 0x12, 0x11, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x73, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x74,
	0x65, 0x43, 0x69, 0x74, 0x79, 0x1a, 0x14, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x73, 0x2e, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x62, 0x65, 0x6c, 0x64, 0x73, 0x22, 0x00, 0x32, 0xb9, 0x02,
	0x0a, 0x07, 0x46, 0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d, 0x12, 0x40, 0x0a, 0x13, 0x72, 0x65, 0x74,
	0x75, 0x72, 0x6e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x62, 0x65, 0x6c, 0x64, 0x73,
	0x12, 0x11, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x73, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x65, 0x43,
	0x69, 0x74, 0x79, 0x1a, 0x14, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x73, 0x2e, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x52, 0x65, 0x62, 0x65, 0x6c, 0x64, 0x73, 0x22, 0x00, 0x12, 0x2a, 0x0a, 0x07, 0x61,
	0x64, 0x64, 0x43, 0x69, 0x74, 0x79, 0x12, 0x0f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x73, 0x2e, 0x44,
	0x61, 0x74, 0x61, 0x43, 0x69, 0x74, 0x79, 0x1a, 0x0c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x73, 0x2e,
	0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x22, 0x00, 0x12, 0x33, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x15, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x73, 0x2e, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x43, 0x69, 0x74, 0x79, 0x1a, 0x0c, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x73, 0x2e, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x22, 0x00, 0x12, 0x2f, 0x0a, 0x0c,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x0f, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x73, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x43, 0x69, 0x74, 0x79, 0x1a, 0x0c, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x73, 0x2e, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x22, 0x00, 0x12, 0x2f, 0x0a,
	0x0a, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x69, 0x74, 0x79, 0x12, 0x11, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x73, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x65, 0x43, 0x69, 0x74, 0x79, 0x1a, 0x0c,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x73, 0x2e, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x22, 0x00, 0x12, 0x29,
	0x0a, 0x08, 0x67, 0x65, 0x74, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x0d, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x73, 0x2e, 0x50, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x1a, 0x0c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x73, 0x2e, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x22, 0x00, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x43, 0x6f, 0x64, 0x65, 0x5a, 0x65, 0x6f, 0x2f,
	0x54, 0x33, 0x2d, 0x53, 0x44, 0x2f, 0x4c, 0x61, 0x62, 0x33, 0x5f, 0x53, 0x44, 0x2f, 0x63, 0x6f,
	0x6d, 0x6d, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_comms_comms_proto_rawDescOnce sync.Once
	file_comms_comms_proto_rawDescData = file_comms_comms_proto_rawDesc
)

func file_comms_comms_proto_rawDescGZIP() []byte {
	file_comms_comms_proto_rawDescOnce.Do(func() {
		file_comms_comms_proto_rawDescData = protoimpl.X.CompressGZIP(file_comms_comms_proto_rawDescData)
	})
	return file_comms_comms_proto_rawDescData
}

var file_comms_comms_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_comms_comms_proto_goTypes = []interface{}{
	(*Conn)(nil),           // 0: comms.Conn
	(*Empty)(nil),          // 1: comms.Empty
	(*Command)(nil),        // 2: comms.Command
	(*LocateCity)(nil),     // 3: comms.LocateCity
	(*NumberRebelds)(nil),  // 4: comms.NumberRebelds
	(*DataCity)(nil),       // 5: comms.DataCity
	(*ChangeNameCity)(nil), // 6: comms.ChangeNameCity
	(*Clock)(nil),          // 7: comms.clock
	(*Planet)(nil),         // 8: comms.Planet
}
var file_comms_comms_proto_depIdxs = []int32{
	2, // 0: comms.Broker.getIP:input_type -> comms.Command
	3, // 1: comms.Broker.getNumberRebelds:input_type -> comms.LocateCity
	3, // 2: comms.Fulcrum.returnNumberRebelds:input_type -> comms.LocateCity
	5, // 3: comms.Fulcrum.addCity:input_type -> comms.DataCity
	6, // 4: comms.Fulcrum.updateName:input_type -> comms.ChangeNameCity
	5, // 5: comms.Fulcrum.updateNumber:input_type -> comms.DataCity
	3, // 6: comms.Fulcrum.deleteCity:input_type -> comms.LocateCity
	8, // 7: comms.Fulcrum.getClock:input_type -> comms.Planet
	0, // 8: comms.Broker.getIP:output_type -> comms.Conn
	4, // 9: comms.Broker.getNumberRebelds:output_type -> comms.NumberRebelds
	4, // 10: comms.Fulcrum.returnNumberRebelds:output_type -> comms.NumberRebelds
	7, // 11: comms.Fulcrum.addCity:output_type -> comms.clock
	7, // 12: comms.Fulcrum.updateName:output_type -> comms.clock
	7, // 13: comms.Fulcrum.updateNumber:output_type -> comms.clock
	7, // 14: comms.Fulcrum.deleteCity:output_type -> comms.clock
	7, // 15: comms.Fulcrum.getClock:output_type -> comms.clock
	8, // [8:16] is the sub-list for method output_type
	0, // [0:8] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_comms_comms_proto_init() }
func file_comms_comms_proto_init() {
	if File_comms_comms_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_comms_comms_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Conn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comms_comms_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comms_comms_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comms_comms_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocateCity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comms_comms_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NumberRebelds); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comms_comms_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataCity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comms_comms_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeNameCity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comms_comms_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Clock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comms_comms_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Planet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_comms_comms_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_comms_comms_proto_goTypes,
		DependencyIndexes: file_comms_comms_proto_depIdxs,
		MessageInfos:      file_comms_comms_proto_msgTypes,
	}.Build()
	File_comms_comms_proto = out.File
	file_comms_comms_proto_rawDesc = nil
	file_comms_comms_proto_goTypes = nil
	file_comms_comms_proto_depIdxs = nil
}
